In [12]:
# 1)Write a Python program to check if a number is prime
def is_prime(n):
    if n<2: 
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0: 
            return False
    return True
is_prime(97)

True

In [13]:
# 2)Create a Fibonacci sequence generator using recursion
def fib(n):
    if n<=0: 
        return []
    if n==1: 
        return [0]
    if n==2: 
        return [0, 1]
    seq=fib(n-1)
    seq.append(seq[-1]+seq[-2])
    return seq
fib(15)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]

In [14]:
# 3)Write a function to find the Greatest Common Divisor (GCD) and Least Common Multiple (LCM) of two numbers
def gcd_lcm(a,b):
    def gcd(x,y):
        while y: 
            x,y=y,x%y
        return x
    gcd_val=gcd(a,b)
    return gcd_val,(a*b)//gcd_val
gcd_lcm(10,20)

(10, 20)

In [17]:
# 4)Build a simple calculator using functions
def calci(a,b,op):
    if op=='+': 
        return a+b
    if op=='-': 
        return a-b
    if op=='*': 
        return a*b
    if op=='/': 
        return a/b if b!=0 else "Cannot divide by zero"
calci(5,4,"*")

20

In [18]:
# 5)Implement a program that takes a list and removes duplicates
def remove_duplicates(li):
    return list(set(li))
li=[1,2,2,3,4,5,5]
remove_duplicates(li)

[1, 2, 3, 4, 5]

In [19]:
# 6)Create a dictionary, add five key-value pairs, and print them
def create_dict():
    d={"a":1,"b":2,"c":3,"d":4,"e":5}
    for k,v in d.items():
        print(k,":",v)
create_dict()

a : 1
b : 2
c : 3
d : 4
e : 5


In [22]:
# 7)Use NumPy to perform basic matrix operations
import numpy as np
def matrix_op():
    A=np.array([[1,2],[3,4]])
    B=np.array([[5,6],[7,8]])
    return np.add(A,B),np.subtract(A,B),np.multiply(A,B),np.dot(A,B)
matrix_op()

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[19, 22],
        [43, 50]]))

In [8]:
# 8)Read a CSV file using pandas and display the first 5 rows
import pandas as pd
def read_csv():
    df=pd.read_csv("file_name.csv")
    return df.head()

In [20]:
# 9)Write a function that finds the most common word in a given text
from collections import Counter
def most_common_word(text):
    words=text.split()
    return Counter(words).most_common(1)[0]
most_common_word("this this is a file")

('this', 2)

In [21]:
# 10)Create a function that generates a random password with a mix of uppercase, lowercase, digits, and special characters
import random
import string
def generate_password(length=12):
    characters=string.ascii_letters+string.digits+string.punctuation
    return ''.join(random.choice(characters) for i in range(length))
generate_password()

'<C"c}M:*-FLm'